// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: donasi.proto

package proto_donasi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DonasiService service

type DonasiService interface {
	GetTransaction2(ctx context.Context, in *APIREQ, opts ...client.CallOption) (*APIRES, error)
}

type donasiService struct {
	c    client.Client
	name string
}

func NewDonasiService(name string, c client.Client) DonasiService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "donasi"
	}
	return &donasiService{
		c:    c,
		name: name,
	}
}

func (c *donasiService) GetTransaction2(ctx context.Context, in *APIREQ, opts ...client.CallOption) (*APIRES, error) {
	req := c.c.NewRequest(c.name, "DonasiService.GetTransaction2", in)
	out := new(APIRES)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DonasiService service

type DonasiServiceHandler interface {
	GetTransaction2(context.Context, *APIREQ, *APIRES) error
}

func RegisterDonasiServiceHandler(s server.Server, hdlr DonasiServiceHandler, opts ...server.HandlerOption) error {
	type donasiService interface {
		GetTransaction2(ctx context.Context, in *APIREQ, out *APIRES) error
	}
	type DonasiService struct {
		donasiService
	}
	h := &donasiServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DonasiService{h}, opts...))
}

type donasiServiceHandler struct {
	DonasiServiceHandler
}

func (h *donasiServiceHandler) GetTransaction2(ctx context.Context, in *APIREQ, out *APIRES) error {
	return h.DonasiServiceHandler.GetTransaction2(ctx, in, out)
}
